[Feat] JwtAuthenticationFilter 생성 및 FilterChain에 등록 (#22)
DeveloperAcademy-POSTECH/MacC-Team-EarthValley80-Server pull request #26
Opened 2022-10-30 14:55 UTC by leobang17

## 작업 개요

JwtAuthenticationFilter 생성 및 FilterChain에 등록

## 이슈 티켓

#22 

## 작업 분류
- [ ] 버그 수정
- [x] 신규 기능
- [ ] 프로젝트 구조 변경
- [ ] 테스트 코드 작성
- [ ] 설정

## 작업 상세 내용
  3. 

## 특이사항 

Filter 등록의 경우 테스트코드 작성이 어려워 생략했습니다.
다만 FilterChainProxy를 이용해 등록된 filter를 로깅하여 해당 필터가 등록되었음을 확인했습니다.

2022-10-31 15:49 UTC, jola7373 requested changes
굿굿 수고하셨어용!

2022-10-31 15:49 UTC, jola7373 commented on src/main/java/com/ada/earthvalley/yomojomo/configs/SecurityConfig.java
> +import org.springframework.security.web.authentication.www.BasicAuthenticationFilter;
p2
import 순서 바꿔주세용~

2022-10-31 15:49 UTC, jola7373 commented on src/main/java/com/ada/earthvalley/yomojomo/auth/JwtAuthenticationFilter.java
> +    }
Q
이건 무슨 메서드인가요?

2022-10-31 15:49 UTC, jola7373 commented on src/main/java/com/ada/earthvalley/yomojomo/auth/JwtAuthenticationFilter.java
> +import java.io.IOException;
p2
import 순서 바꿔줘욥

2022-11-01 02:37 UTC, leobang17 commented on src/main/java/com/ada/earthvalley/yomojomo/auth/JwtAuthenticationFilter.java
> +    }
shouldNotFilter가 true를 반환하면 해당 필터는 처리되지 않습니다. 
url 패턴따라, 혹은 기타 조건 하에 필터를 활성화/비활성화 하고 싶은 경우 이용할 수 있습니다.
지금은 무조건 false를 반환하기 때문에 필터 등록 시 제약조건을 걸지 않는이상 모든 request에 대해 활성화 됩니다.

2022-11-01 02:38 UTC, jola7373 approved these changes

2022-11-01 02:40 UTC, merged