[Feat] AuthenticationConverter 정의 및 테스트
DeveloperAcademy-POSTECH/MacC-Team-EarthValley80-Server pull request #27
Opened 2022-10-30 14:59 UTC by leobang17

## 작업 개요

AuthenticationConverter의 구현체인 AuthorizationConverter를 정의하고 테스트 하였습니다. 

## 이슈 티켓

#25 

## 작업 분류
- [ ] 버그 수정
- [x] 신규 기능
- [ ] 프로젝트 구조 변경
- [x] 테스트 코드 작성
- [ ] 설정

## 작업 상세 내용

- HttpRequest의 Authorization header에서 Bearer 토큰을 파싱해 인증객체에 담아 반환하는 AuthorizationConverter를 정의하고 테스트함.
- 이에 수반되는 Security 관련 Component들의 껍데기를 정의했습니다. 

## 생각해볼 문제

- 현재 껍데기만 만들어놓은 Security 관련 Component를 더 디벨롭 해야겠습니다.

2022-10-31 17:01 UTC, jola7373 requested changes
수우우우고 하셨습니다아아아아!!!

2022-10-31 17:01 UTC, jola7373 commented on src/main/java/com/ada/earthvalley/yomojomo/auth/jwt/AuthorizationConverter.java
> +public class AuthorizationConverter implements AuthenticationConverter {
p3
authentication 의 자식 클래스로 authorization이 있어도 될지 저는 조금 헤깔리는 것 같아유

2022-11-01 00:27 UTC, leobang17 commented on src/main/java/com/ada/earthvalley/yomojomo/auth/jwt/AuthorizationConverter.java
> +public class AuthorizationConverter implements AuthenticationConverter {
Authorization 헤더의 Bearer scheme을 파싱해서 인증 객체로 가져오는 역할이라 AuthorizationConverter로 이름 지었어요
BearerAuthenticationConverter로 변경하는게 나을 것 같네여. 굿굿

2022-11-01 00:28 UTC, leobang17 commented
@jola7373 컨벤션 수정사항들은 CheckStyle 적용 이후에 일괄적으로 적용하겠습니다.

2022-11-01 02:39 UTC, jola7373 approved these changes

2022-11-01 02:41 UTC, merged