[Feat] Exception Handler 및 ErrorResponse 정의 (#28)
DeveloperAcademy-POSTECH/MacC-Team-EarthValley80-Server pull request #31
Opened 2022-10-31 07:48 UTC by leobang17

## 작업 개요

Exception Handler 및 ErrorResponse 정의

## 이슈 티켓

#28 

## 작업 분류
- [ ] 버그 수정
- [x] 신규 기능
- [ ] 프로젝트 구조 변경
- [x] 테스트 코드 작성
- [x] 설정

## 작업 상세 내용
 
**main**
- ExceptionHandler 역할을 하는 GlobalExceptionHandler 정의
- ErrorResponse 정의
- 애플리케이션 로직 안에서 던지는 Exception 의 부모가 되는 YomojomoException 정의
- 내부 에러코드가 담긴 ErrorCode 정의
- 각 domain 별로 정의할 error enum의 interface인 ErrorInfo 정의

**test**
- 테스트에 수반되는 테스트 클래스들 정의 (TestError, YomojomoTestException, ExceptionTestController)

## 생각해볼 문제

ErrorCode를 어디서 어떻게 관리할지 좀 더 고민해봐야겠다.

2022-10-31 08:18 UTC, jola7373 commented on src/main/java/com/ada/earthvalley/yomojomo/common/exceptions/ErrorCode.java
> +import org.springframework.http.HttpStatus;
p2
import 순서 정렬해주세욥
<img width="409" alt="스크린샷 2022-10-31 오후 5 18 41" src="https://user-images.githubusercontent.com/62223855/198962855-110277f0-54cc-43e6-b493-11c10358bbc2.png">

2022-10-31 08:38 UTC, jola7373 requested changes
굿굿 감사합니다!~!
수고하셨습니당~
전반적으로 코드스타일에 대한 코멘트를 많이 달아봤어요! 한번쯤은 이렇게 코딩 컨벤션 지켜가면서 하고 싶어서용~!

2022-10-31 08:38 UTC, jola7373 commented on src/main/java/com/ada/earthvalley/yomojomo/common/exceptions/ErrorCode.java
> +
p2 
불 필요한 빈줄 삭제 어때유?

2022-10-31 08:38 UTC, jola7373 commented on src/main/java/com/ada/earthvalley/yomojomo/common/exceptions/ErrorCode.java
> +import org.springframework.http.HttpStatus;
p2
import 순서 정렬해봅세당
<img width="402" alt="스크린샷 2022-10-31 오후 5 20 09" src="https://user-images.githubusercontent.com/62223855/198963140-e1459214-a22b-49de-8124-f433277ab56e.png">

그리고 각 그룹 사이에 빈줄 삽입 please

2022-10-31 08:38 UTC, jola7373 commented on src/main/java/com/ada/earthvalley/yomojomo/common/exceptions/ErrorInfo.java
> +
p2
여기도 빈줄 없애도 될것 같아용

2022-10-31 08:38 UTC, jola7373 commented on src/main/java/com/ada/earthvalley/yomojomo/common/exceptions/ErrorResponse.java
> +import java.time.LocalDateTime;
p2 
여기도 아까 말한 import 순서 정렬 & 그룹 별로 빈줄 삽입 부탁해용

2022-10-31 08:38 UTC, jola7373 commented on src/main/java/com/ada/earthvalley/yomojomo/common/exceptions/ErrorResponse.java
> +
p2
여기도 빈 줄 삭제부탁해용

2022-10-31 08:38 UTC, jola7373 commented on src/main/java/com/ada/earthvalley/yomojomo/common/exceptions/handler/GlobalExceptionHandler.java
> +import org.springframework.web.bind.annotation.RestControllerAdvice;
p2
import 순서 & 그룹별 그룹핑 please

2022-10-31 08:38 UTC, jola7373 commented on src/test/java/com/ada/earthvalley/yomojomo/common/exceptions/ExceptionTestController.java
> +import org.springframework.web.bind.annotation.RestController;
p2
여기도 import 순서... & 그룹핑...

2022-10-31 08:38 UTC, jola7373 commented on src/test/java/com/ada/earthvalley/yomojomo/common/exceptions/GlobalExceptionHandlerTest.java
> +import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.status;
p2
여기도 순서와 그룹핑 부탁해용~

2022-10-31 08:38 UTC, jola7373 commented on src/main/java/com/ada/earthvalley/yomojomo/common/exceptions/ErrorResponse.java
> +    private String stateToString(HttpStatus status) {
Q
여기서 state은 무엇을 의미하나요?

2022-10-31 08:38 UTC, jola7373 commented on src/main/java/com/ada/earthvalley/yomojomo/common/exceptions/YomojomoException.java
> +public class YomojomoException extends RuntimeException {
Q
이거 예시인거져?

2022-10-31 08:41 UTC, leobang17 commented on src/main/java/com/ada/earthvalley/yomojomo/common/exceptions/ErrorResponse.java
> +    private String stateToString(HttpStatus status) {
Spring에서 제공하는 HttpStatus enum 클래스입니다.
Http status를 편리하게 만들 수 있어요.

2022-10-31 08:42 UTC, leobang17 commented on src/main/java/com/ada/earthvalley/yomojomo/common/exceptions/YomojomoException.java
> +public class YomojomoException extends RuntimeException {
아니욥
앞으로 우리 비즈니스 로직 안에서 일어나는 모든 exception은 이 exception 클래스를 상속하면 됩니다. 
이 클래스를 상속해야 ExceptionHandler가 감지해서 지정한 handler 메서드로 처리를 위임해줘요.

2022-10-31 15:02 UTC, leobang17 commented on src/main/java/com/ada/earthvalley/yomojomo/common/exceptions/ErrorInfo.java
> +
반영 完
[4d7949a](https://github.com/DeveloperAcademy-POSTECH/MacC-Team-EarthValley80-Server/pull/31/commits/4d7949ae533a9b6b0c539183f93d16ced059df64)

2022-10-31 15:02 UTC, leobang17 commented on src/main/java/com/ada/earthvalley/yomojomo/common/exceptions/ErrorCode.java
> +import org.springframework.http.HttpStatus;
반영 完
[4d7949a](https://github.com/DeveloperAcademy-POSTECH/MacC-Team-EarthValley80-Server/pull/31/commits/4d7949ae533a9b6b0c539183f93d16ced059df64)

2022-10-31 15:03 UTC, leobang17 commented
@jola7373 제가 지금 style guild 적용 에러가 난 상태인데 혹시 설치후에 공백같은 컨벤션 수정할 수 있을까요 ?
일단 import 순서는 수정했습니다

2022-11-01 02:39 UTC, jola7373 approved these changes

2022-11-01 02:43 UTC, merged