[Feat] ERD -> JPA 엔티티 매핑
DeveloperAcademy-POSTECH/MacC-Team-EarthValley80-Server pull request #39
Opened 2022-11-02 14:07 UTC by leobang17

## 작업 개요

ERD -> JPA 엔티티 매핑 

## 이슈 티켓

#38 

## 작업 분류
- [ ] 버그 수정
- [x] 신규 기능
- [x] 프로젝트 구조 변경
- [ ] 테스트 코드 작성
- [x] 설정

## 작업 상세 내용

- ERD를 JPA에 매핑했습니다.
- application.yml을 수정했습니다.
  - main path에 spring.jpa.properties.hibernate.globally_quoted_identifiers = true 추가
    - 예약어 충돌 회피를 위함.
    - test path 에 h2 embedded 설정 (PostgreSQL compatibility)
- SecurityConfig의 디렉토리를 이동했습니다.
- Entity에 대해서 각자 테스트를 진행하고 싶었지만 test scope을 entity 단위로 줄이는 방법은 시도해봤는데 잘 안되네요...
  - 일단 @DataJpaTest로 모든 entity에 대해 생성되었는지 일괄적으로 확인했습니다.

## 생각해볼 문제

GroupUser 가 orphan 이 되어서 삭제된다면 NIE 는 어떻게 되어야 할까? 
Group 이 삭제되었을 때 NIE 와 긴밀한 관계가 있는 GroupUser 는 어떻게 되야할까
Test scope을 entity 단위로 좁히는 방법은 뭐가 있을까

2022-11-02 20:26 UTC, jola7373 reviewed
내일 이어서 할래여....ㅠㅠ 죄송해요..ㅠㅠ 진짜..ㅠㅠ

2022-11-02 20:26 UTC, jola7373 commented on src/main/java/com/ada/earthvalley/yomojomo/group/entities/Group.java
> +	@OneToMany(mappedBy = "group", cascade = CascadeType.ALL, orphanRemoval = true)
p3 
흠.. 그 점을 고려하면 NIE와 User가 매핑되어 있어야 할것 같은디요...

2022-11-03 00:18 UTC, leobang17 commented on src/main/java/com/ada/earthvalley/yomojomo/article/entities/Topic.java
> +public class Topic extends BaseEntity {
Topic - User가 다대다관계를 가지기로 했었습니다. 조인테이블로 `UserTopic`이 있습니다.

2022-11-03 00:20 UTC, jola7373 commented on src/main/java/com/ada/earthvalley/yomojomo/article/entities/Topic.java
> +public class Topic extends BaseEntity {
그때 왜 enum을 사용하지 않고 테이블로 빼기로 했는지 기억이 안나서유

2022-11-03 00:22 UTC, leobang17 commented on src/main/java/com/ada/earthvalley/yomojomo/group/entities/Group.java
> +	@OneToMany(mappedBy = "group", cascade = CascadeType.ALL, orphanRemoval = true)
@jola7373 
기획 회의를 통해 이야기를 좀 더 이야기를 해보시져 . . 
방을 나가면 본인의 기록이 모두 지워져도 괜찮은지 아님 개인 활동하는 공간에 아카이빙 되어야 하는지
ios 메모처럼 만료기간을 두고 휴지통 기능을 생각해도 괜찮을듯 ??!

2022-11-03 01:14 UTC, leobang17 commented on src/main/java/com/ada/earthvalley/yomojomo/article/entities/Topic.java
> +public class Topic extends BaseEntity {
@jola7373 
enum을 이용하면 
유저 A와 유저 B가 동일하게 "경제" 토픽을 추가하더라도 enum의 경우 값비교를 통해 동일함을 검증하기 때문에 논리적으로 동일한 테이블 row를 참조하고 있는 다대다 관계보다 확장성이 낮다고 판단해서 
였던 것 같네요.

2022-11-03 01:52 UTC, jola7373 requested changes
수고하셨습니다아!! 
꼼꼼히 보려다 보니 꽤 시간이 걸렸네요..

Entity layer의 테스트 코드를 저도 꽤 찾아 봤었는데 entity class에 있는 제대로 기능하지 않을 수 있는 모든 메서드들에 대한 테스트를 진행하더라고요. 

그런데 현재는 getter만이 존재하고 getter가 문제를 일으킬만한 문제가 생기는 것 같지 않아서 저는 일단은 필요 없지만 추가적인 메서드들이 생기면 그때 작성하는거 어떤가요?

또 도메인 지식을 설명하는 용도로도 사용하기 좋다고 하니 차차 작성해보는게 좋을 것 같아요

### 참고 링크
- https://stackoverflow.com/questions/674408/junit-tests-for-pojos
- https://cheese10yun.github.io/spring-about-test/

2022-11-03 02:27 UTC, leobang17 commented on src/main/java/com/ada/earthvalley/yomojomo/user/entities/User.java
> +public class User extends BaseEntity {
@jola7373 
application.yml의 spring.jpa.properties.hibernate.globally_quoted_identifiers 프로퍼티 속성을 true로 주었습니다. 
<img width="543" alt="image" src="https://user-images.githubusercontent.com/77837101/199635784-e7425223-9c68-42c6-8d62-add248f50ac2.png">
DDL 실행 시 모든 table에 대해 `"` quote로 감싸주는 역할을 합니다.  
이를 이용해 예약어 충돌을 회피할 수 있습니다.
group 역시 PostgreSQL 예약어지만 해당 프로퍼티를 이용해 예약어 충돌을 회피했습니다. 

hibernate가 제공하는 property option 레퍼런스
https://docs.jboss.org/hibernate/orm/5.2/userguide/html_single/appendices/Configurations.html

2022-11-03 02:30 UTC, leobang17 commented on src/main/java/com/ada/earthvalley/yomojomo/user/entities/User.java
> +@NoArgsConstructor(access = AccessLevel.PUBLIC)
아ㅏㅏ 이거 저 그냥 개인적으로 테스트코드 짜느라 public으로 돌렸는데 까먹고 안바꾸고 push 해버렸네요... 이부분은 수정하겠습니다.

2022-11-03 03:04 UTC, leobang17 commented on src/main/java/com/ada/earthvalley/yomojomo/auth/entities/RefreshToken.java
> +@Embeddable
RefreshToken이 별도의 테이블로 존재해야할 이유를 못느껴서 값타입으로 정의했습니다.
RefreshToken에 읽기 및 쓰기 작업이 일어나는 상황은 
- reissue api
  -  jwt 파싱하여 user_id 얻고
  - user_id로 User 엔티티 조회 
  - 객체 그래프로 RefreshToken 조회
  - 확인 후 새로운 access token 발급하며 RefreshToken도 새로 덮어씌우기
이 될텐데
RefreshToken 테이블 자체를 독립적으로 서칭할 필요가 없고, RefreshToken의 변경사항이 세밀하지 않다는 점 (항상 통째로 변경됨)에서  값타입으로 정의했습니다. 
혹시 다온이 생각하기에 엔티티로 정의하고자 하는 이유가 있을까요?

2022-11-03 06:42 UTC, leobang17 commented on src/main/java/com/ada/earthvalley/yomojomo/user/entities/User.java
> +@NoArgsConstructor(access = AccessLevel.PUBLIC)
[095fae8](https://github.com/DeveloperAcademy-POSTECH/MacC-Team-EarthValley80-Server/pull/39/commits/095fae8b56496bf305d22dcc281fdf7a3587908a)

반영 完

2022-11-03 06:49 UTC, jola7373 commented on src/main/java/com/ada/earthvalley/yomojomo/user/entities/User.java
> +public class User extends BaseEntity {
실제로 native query날릴때 인용부호로 감싸야하고 
<img width="555" alt="스크린샷 2022-11-03 오후 3 49 20" src="https://user-images.githubusercontent.com/62223855/199661740-fb9888ab-f994-452d-b627-ea392e57bfc3.png">

저희의 naming 규칙에 따라 해당사항은 미래에 불편함을 나을듯 합니당

2022-11-03 06:49 UTC, jola7373 commented on src/main/java/com/ada/earthvalley/yomojomo/auth/entities/RefreshToken.java
> +@Embeddable
추후에 redis cache서버로 분리할때 이렇게 설계하는것이 이전에 더 편하다고 판단했기 때문입니당

2022-11-03 06:50 UTC, jola7373 commented on src/main/java/com/ada/earthvalley/yomojomo/group/entities/Group.java
> +	@OneToMany(mappedBy = "group", cascade = CascadeType.ALL, orphanRemoval = true)
좋습니당

2022-11-03 06:55 UTC, leobang17 commented on src/main/java/com/ada/earthvalley/yomojomo/user/entities/User.java
> +public class User extends BaseEntity {
@jola7373 
[a69e732](https://github.com/DeveloperAcademy-POSTECH/MacC-Team-EarthValley80-Server/pull/39/commits/a69e7327297136e194e3736f3258bacfda297c79)

반영 完

2022-11-03 06:56 UTC, leobang17 commented on src/main/java/com/ada/earthvalley/yomojomo/auth/entities/RefreshToken.java
> +@Embeddable
@jola7373 
[6567344](https://github.com/DeveloperAcademy-POSTECH/MacC-Team-EarthValley80-Server/pull/39/commits/6567344ed3f822aaefeb159626a2452759dc245d)
반영 完

2022-11-03 06:59 UTC, jola7373 approved these changes

2022-11-03 07:01 UTC, merged