Config/2 project config
DeveloperAcademy-POSTECH/MacC-Team-EarthValley80-Server pull request #5
Opened 2022-10-17 13:31 UTC by leobang17

### 작업 개요

프로젝트 생성 및 설정 

### 이슈 티켓

#2 

### 작업 분류
- [ ] 버그 수정
- [ ] 신규 기능
- [ ] 프로젝트 구조 변경
- [ ] 테스트 코드 작성
- [v] 설정

### 작업 상세 내용
  3. 
application.yml 설정함
- AWS 연동하기 전 이용할 local postgresql 연결 설정
  -  **PostgreSQL 로컬에 'nier' 이름의 DB 생성해주세요!!!!!!!! ** 
- dev 환경의 `ddl-auto` 전략은 create

SecurityConfig 설정함
- 일단은 기본적으로 적용되는 모든 security 설정 없앰 

### 생각해볼 문제

 **PostgreSQL 로컬에 'nier' 이름의 DB 생성해주세요!!!!!!!! ** 
 **PostgreSQL 로컬에 'nier' 이름의 DB 생성해주세요!!!!!!!! ** 
 **PostgreSQL 로컬에 'nier' 이름의 DB 생성해주세요!!!!!!!! **

2022-10-17 16:05 UTC, jola7373 requested changes
Hey Fart!! 
수고하셨습니다!! 프로젝트 세팅만 딱 깔끔하네요!! 
단지 .idea에서 gitignore시키면 좋겠는것들은 ignore시켜서 관리하는게 편할것 같아요!!

2022-10-18 00:37 UTC, leobang17 commented on .idea/gradle.xml
> +</project>
@jola7373 
일단 gitignore 자동생성기에서 생성했는데 뭘 넣고 뺄지는 고민을 안해봤네요 . . . . 
함께 보시져

2022-10-18 00:38 UTC, leobang17 commented on HELP.md
> +# Getting Started
@jola7373 글쎄요 . . . . ?

2022-10-18 01:22 UTC, jola7373 commented on .idea/gradle.xml
> +</project>
넵넵!!

2022-10-18 05:22 UTC, leobang17 commented on .idea/gradle.xml
> +</project>
ed5d81cd1935ee17d74823d4dacdd3bd43cd306b

.gitignore 반영완료

2022-10-18 05:22 UTC, leobang17 commented on HELP.md
> +# Getting Started
ed5d81cd1935ee17d74823d4dacdd3bd43cd306b

.gitignore 반영완료

2022-10-18 05:47 UTC, jola7373 approved these changes

2022-10-18 05:56 UTC, merged