[Feat] Topic 관련 API 구현
DeveloperAcademy-POSTECH/MacC-Team-EarthValley80-Server pull request #72
Opened 2022-12-01 02:33 UTC by leobang17

# 작업 개요

GET 토픽 불러오기 API
POST 토픽 설정하기 API 

# 이슈 티켓

- #68 

# 작업 분류
- [ ] 버그 수정
- [x] 신규 기능
- [x] 프로젝트 구조 변경
- [x] 테스트 코드 작성
- [ ] 설정

# 작업 상세 내용
  3. 

### Topic 관련 Entity Layer의 변경사항
- Topic은 이제 대분류, 소분류로 구분된다. (MajorTopicType, SubTopicType)
- 기존의 TopicType 삭제
- UserTopic의 생성 편의 메서드 추가
- UserTopicRepository, TopicRepository 추가

### Topic 관련 Repository Layer 테스트
- 디폴트 토픽을 생성하는 data.sql 정의
- test path의 application.yml에 Hibernate가 .sql 스크립트보다 먼저 실행되도록 defer-datasource-initialization 추가

TopicRepositoryTest
- 모든 토픽 찾기 (성공)

### Topic 관련 Service Layer
- TopicService 구현
  - 모든 토픽 가져오기
  - 선택한 토픽 유저에게 저장하기
- UserDomainService.findByIdOrElseThrow 구현
- TopicError, YomojomoTopicException 정의
- UserError, YomojomoUserException 정의

### Topic 관련 Service Layer 테스트
- TopicConst에 Test에 이용되는 상수 정의
- TopicFixtures 정의

TopicServiceTest
- 모든 토픽 가져오기
  - 성공
- 선택한 토픽 저장하기
  - 성공
  - 실패
    - (case1) 유저 없음
    - (case2) 토픽 없음

UserDomainServiceTest
- 유저 불러오기
  - 성공
  - 실패 (유저 없음)

### Topic 관련 Web Layer 구현
- Jwt 시큐리티 필터체인의 csrf 설정 off
- TopicController 정의
- request, response 정의

### Topic 관련 Web Layer 및 Integration 테스트 진행
TopicControllerTest
- 모든 토픽 가져오기
  - 성공
- 토픽 선택하기
  - 성공
  - 실패
    - (case1) 유저 없음
    - (case2) 토픽 없음

TopicApiIntegrationTest
- 모든 토픽 가져오기
- 토픽 선택하기

### 통합 테스트를 위한 base class 정의 
- BaseIntegrationTest
  - 기본 테스트 유저 정의

# 생각해볼 문제

바쁘다 바빠

2022-12-03 12:26 UTC, jola7373 commented on src/main/java/com/ada/earthvalley/yomojomo/article/dtos/FetchTopicsResponse.java
> +@Data
p2
@Data는 @Setter도 포함하고 있어 객체가 어디서든 바뀔 수 있어 안전하지 않다고 생각되는데 혹시 사용한 이유가 있을까요?

2022-12-03 12:55 UTC, jola7373 requested changes
수우우우우고 하셨습니다...
정말..정말,,,, 바쁘네요,,,,ㅠㅠ
항상 좋은 코드 감사합니다!! 딱 일주일만 더 버텨봅시다!! 저도 Article 얼른해서 올리겠습니다... 감사합니다

2022-12-03 12:55 UTC, jola7373 commented on src/main/java/com/ada/earthvalley/yomojomo/article/dtos/FetchTopicsResponse.java
> +@Data
p2
@Data는 @Setter를 포함하고 있어 사용하지 않는 것이 좋다고 생각합니다. 

이미 아실 수 있겠지만 Setter를 사용하면 객체를 언제든지 변경할 수 있는 상태가 되어 안전하지 않다고 생각합니다.

2022-12-03 12:55 UTC, jola7373 commented on src/main/java/com/ada/earthvalley/yomojomo/article/dtos/FetchTopicsResponse.java
> +public class FetchTopicsResponse {
p2
또 NoArgsConstructor 로 접근을 최소화해야 하지 않을까유?

2022-12-03 12:55 UTC, jola7373 commented on src/test/java/com/ada/earthvalley/yomojomo/article/TopicConst.java
> +}
이렇게 url path만 따로 빼서 관리하는거 되게 편하고 좋은거 같네욥!! 굿굿

2022-12-03 12:55 UTC, jola7373 commented on src/test/java/com/ada/earthvalley/yomojomo/article/api/TopicControllerRestDocs.java
> +	void 모든_토픽_가져오기() throws Exception {
p3
ErrorResponse도 같이 문서화 시키는게 좋을것 같아요!

2022-12-04 01:48 UTC, leobang17 commented on src/main/java/com/ada/earthvalley/yomojomo/article/dtos/FetchTopicsResponse.java
> +@Data
추후에 수정할게요-!

2022-12-04 01:48 UTC, leobang17 commented on src/main/java/com/ada/earthvalley/yomojomo/article/dtos/FetchTopicsResponse.java
> +public class FetchTopicsResponse {
추후에 수정할게요-!

2022-12-04 01:49 UTC, merged